Database parameter will work (#17)
* database parameter will work

sample code:
```python
ch = {'host': 'http://clickhouse:8123', 'database': 'telegraf', 'user': 'test', 'password': 'test'}

QUERY = "SELECT datetime, host, toStringCutToZero(path) AS path, total, free, used, used_percent FROM disk WHERE service = 'backup'"

df = read_clickhouse(QUERY, connection=ch)
```
give me error:

    pandahouse.http.ClickhouseException: Code: 60, e.displayText() = DB::Exception: Table default.disk doesn't exist., e.what() = DB::Exception

* use default database

* fix fixtures

* fix fixtures